name: This is a github action
on: [push]
jobs:
 Echo:
  runs-on: ubuntu-latest
  steps: 
  - name: echo hello
    run: echo hello
 test:
  runs-on: ubuntu-latest
  steps:
  - name: test
    run: echo testing

 build:
  runs-on: ubuntu-latest
  steps:
   - name: build
     run: echo building

 deploy:
  runs-on: ubuntu-latest
  steps:
  - name: deploy
    run: echo deploying
